### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by saimyosett** [cometchat-pro-samples/ios-swift-chat-app#12]
when trying to build the project I got this error

'PiPViewCoordinator' is not a member type of 'JitsiMeet'

**Comment by pushpsenairekar2911** [comment]
Hello @saimyosett,

It seems that pods are not installed properly which are required to run this sample app. Please, follow the instructions mentioned in the readme.md and use 'pod install' command to install require pods. 

Also, we suggest you clean the project and derived data before installing the pods. 

If you're facing any difficulties while running this project, then please report it on https://forum.cometchat.com/.

**Comment by saimyosett** [comment]
still getting error after I did everything you said so I went to the forum as you said and 
I found this.

[https://forum.cometchat.com/t/failed-to-load-module-jitsimeet/932](url)
