### ISSUE TITLE
Sample cannot run in Xcode 11.4

### ISSUE THREAD

**Issue by voyager163** [cometchat-pro-samples/ios-swift-chat-app#13]
**Describe the bug**
The SDK cannot run in XCode 11.4. It is the same issue of jitsi-meet iOS SDK.

**To Reproduce**
You just need to download XCode 11.4 and run it. The error will pop up.

Attached is the image
<img width="1050" alt="Screenshot 2020-04-06 at 9 14 45 AM" src="https://user-images.githubusercontent.com/4599055/78515099-2b8c7f00-77e7-11ea-9ebb-b591737debdc.png">

**Comment by pushpsenairekar2911** [comment]
Hello @voyager163 , 
We have released new version of the Sample app with Xcode 11.4 support. Please, clone the project and use the project to exist in folder Xcode 11.4. This should resolve your issue.

**Comment by voyager163** [comment]
Hi CometChat, 

Thanks for the quick turnaround.

Best Regards,
Jonathan
