### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by wazowski78** [cometchat-pro-samples/ios-swift-chat-app#2]
Hi,
I am getting this message with the sample app:
`../CometChatPro-swift-sampleApp/AppDelegate.swift:10:8: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: ../Pods/CometChatPro/CometChatPro.framework/Modules/CometChatPro.swiftmodule/arm64.swiftmodule`
Can you help me to start with this please?

**Comment by pushpsenairekar2911** [comment]
Hello wazowski78, 

Hope your day is going well.

We're adding support for swift 5.0 for our CometChatPro iOS SDK . For now, you can use and build the same with Xcode 10.1. This should resolve your issue.
We'll update you once the support is added for swift 5.0. 

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,
Pushpsen A.
CometChatPro Team

**Comment by wazowski78** [comment]
Thank you very much for your reply! By the way, does this sample project includes conference video too? I am trying to find the documentation in your web, but I can not find anything useful.

**Comment by pushpsenairekar2911** [comment]
Hello wazowski78, 

Hope your day is going well. 

We don't have a feature like 'conference video' in our SDK. But you can use group video calling if it solves your purpose. You can refer to this [documentation](https://prodocs.cometchat.com/docs/ios-calling) for calling. 

Hope this helps. 

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,

Pushpsen A.
CometChatPro Team

**Comment by wazowski78** [comment]
Hello Pushpen.

Thank you for your reply. I tried to use the sample chat demo on GitHub, but it is not working, I am using the Objective-C demo, but call and video is not working. I have to try the swift version, but I have to test it in a few days.

On more question, I would like to know how many users can use the video call at the same time.

Thank you very much.
M.W.

**Comment by pushpsenairekar2911** [comment]
Hello wazowski78,

Here are my comment to your queries:

1. I tried to use the sample chat demo on GitHub, but it is not working. 
- We have tested our swift demo, It working properly. Kindly, let us know which issue you are facing with the swift chat app. 

2. I am using the Objective-C demo, but call and video is not working. 
- We are working on it. We will update you regarding the same once we release new version fixed with Calling. 

3. I would like to know how many users can use the video call at the same time.
- For best performance 4-6 users can be part of the same video conference.

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,

Pushpsen A.
CometChatPro Team

**Comment by wazowski78** [comment]
Thanks a lot. I will try the swift version, and hope ObjectiveC version will be ready soon.

Best regards,
M.W.

**Comment by pushpsenairekar2911** [comment]
Hello, 

We have added the support for the Swift 5 for our sample apps. You can [refer this link](https://github.com/cometchat-pro-samples/ios-swift-chat-app) to download or clone the repository. 

Hope this helps.

**Comment by pushpsenairekar2911** [comment]
We are closing this ticket. You can re-open this ticket if anything needed.

**Comment by arunblan** [comment]
I had swift 10.2.1
I'm getting this error code (Module compiled with Swift 5.2 cannot be imported by the Swift 5.0.1 compiler: /Users/user/Desktop/cometChatPod/Pods/CometChatPro/CometChatPro.framework/Modules/CometChatPro.swiftmodule/x86_64.swiftmodule)
can you help me with this
