### ISSUE TITLE
Cometchar pod not working on Swift 4.2

### ISSUE THREAD

**Issue by smindia1988** [cometchat-pro-samples/ios-swift-chat-app#5]
Not able to build code after installing Cometchat pod on the project developed on swift 4.2.  How can we install cometchat successfully with swift4.2 code ?

**giving error as below:**
"Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler"

**Comment by pushpsenairekar2911** [comment]
Hello @smindia1988, You can check our sample app for Swift 4.2 using [this link](https://github.com/cometchat-pro/ios-chat-sdk-swift-4.2). Also, you need to add CometChatPro framework manually inside your project as mentioned in the project.
