### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/MyMac./Downloads/Comet-chat/Pods/CometChatPro/CometChatPro.framework/Modules/CometChatPro.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by ShivMiet** [cometchat-pro-samples/ios-swift-chat-app#6]
Hi I update Xcode 11 and getting issue.

**Comment by pushpsenairekar2911** [comment]
@ShivMiet,  We have added the support for Xcode 11. Kindly take the fresh pull and run the project. Also, run the project in the physical device itself.
