### ISSUE TITLE
Ambiguous use of operator and stored property

### ISSUE THREAD

**Issue by akki6230** [cometchat-pro-samples/ios-swift-chat-app#7]
**Added sample swift project to app. My UIView's  *IBDesignables* stoped working and showing these following issues:- **

1. Ambiguous use of operator '=='
2. Cannot override with a stored property 'cornerRadius' 
3. Cannot override with a stored property  'shadowOpacity',
4. Cannot override with a stored property 'shadowColor',  
5. Cannot override with a stored property 'shadowOpacity'
6. Cannot override with a stored property 'shadowRadius'

Please help me in this. 
Thanks

**Comment by pushpsenairekar2911** [comment]
Closing this issue. No action needed
