### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by SPIf4A** [cometchat-pro-samples/ios-swift-chat-app#8]
CometChatPro-swift-sampleApp[46732:5466029] Task <826DC470-5648-4BC2-BE14-9635B5A12C03>.<7> HTTP load failed (error code: -1003 [12:8])CometChatPro-swift-sampleApp[46732:5466029] Task <826DC470-5648-4BC2-BE14-9635B5A12C03>.<7> HTTP load failed (error code: -1003 [12:8])CometChatPro-swift-sampleApp[46732:5466029] Task <826DC470-5648-4BC2-BE14-9635B5A12C03>.<7> HTTP load failed (error code: -1003 [12:8])

**Comment by SPIf4A** [comment]
Cometchat Support is very slow. Cant use longterm

**Comment by anantgarg** [comment]
@SPIf4A if you need quicker support, feel free to join our Slack channel- 

https://slack.cometchat.com

We are available 24/5.

**Comment by pushpsenairekar2911** [comment]
@SPIf4A, Are you able to login now? If you're facing any issue then you can report here as well as on our slack community channel.

**Comment by anantgarg** [comment]
@SPIf4A has this been resolved?

**Comment by pushpsenairekar2911** [comment]
Closing this ticket. No action needed.
