### ISSUE TITLE
App crash when run on real device/simulator(Xcode 11)

### ISSUE THREAD

**Issue by HienNguyen102** [cometchat-pro-samples/ios-swift-chat-app#9]
I used lasted version of SDK, both v1.8 or v2.0 (Source in Xcode 11 folder). Xcode build successfully but app run on device/simulator crash immediately
These are crash log:
dyld: Library not loaded: @rpath/JitsiMeet.framework/JitsiMeet
  Referenced from: /private/var/containers/Bundle/Application/5530BF2A-57F6-4174-A69E-81AD310906E7/CometChatPro-swift-sampleApp.app/Frameworks/CometChatPro.framework/CometChatPro
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/5530BF2A-57F6-4174-A69E-81AD310906E7/CometChatPro-swift-sampleApp.app/Frameworks/JitsiMeet.framework/JitsiMeet: file too short
	/private/var/containers/Bundle/Application/5530BF2A-57F6-4174-A69E-81AD310906E7/CometChatPro-swift-sampleApp.app/Frameworks/JitsiMeet.framework/JitsiMeet: file too short
	/private/var/containers/Bundle/Application/5530BF2A-57F6-4174-A69E-81AD310906E7/CometChatPro-swift-sampleApp.app/Frameworks/JitsiMeet.framework/JitsiMeet: file too short
	/private/var/containers/Bundle/Application/5530BF2A-57F6-4174-A69E-81AD310906E7/CometChatPro-swift-sampleApp.app/Frameworks/JitsiMeet.framework/JitsiMeet: file too short

**Comment by pushpsenairekar2911** [comment]
@HienNguyen102  We have updated our sample app. Please take the fresh clone and then perform the instructions specified in readme.md file.
